
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


CREATE SCHEMA IF NOT EXISTS `flors` DEFAULT CHARACTER SET utf8 ;
USE `flors` ;


CREATE TABLE IF NOT EXISTS `flors`.`llista_flors` (
  `pk_FlorID` INT(11) NOT NULL AUTO_INCREMENT,
  `nomFlor` VARCHAR(45) NOT NULL,
  `paisFlor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pk_FlorID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;